# Generated by Django 5.1 on 2024-08-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.IntegerField()),
                ('ticketServicePlatform', models.CharField(choices=[('jira', 'JIRA'), ('freshservice', 'Freshservice')], default='', max_length=20)),
                ('plannedStartDate', models.DateTimeField()),
                ('plannedEffort', models.TimeField()),
                ('subject', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(default=None)),
                ('departmentId', models.IntegerField(default=None)),
                ('category', models.CharField(default=None, max_length=255)),
                ('subCategory', models.CharField(default=None, max_length=255)),
                ('itemCategory', models.CharField(default=None, max_length=255)),
                ('requesterId', models.IntegerField()),
                ('responderId', models.IntegerField()),
                ('emailConfigId', models.CharField(default=None, max_length=255)),
                ('fwdMails', models.TextField(default='[]')),
                ('isEscalated', models.BooleanField(default=False)),
                ('frDueBy', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('workSpaceId', models.IntegerField()),
                ('requestedForId', models.IntegerField()),
                ('toEmails', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('descriptionHTML', models.TextField()),
                ('majorIncidentType', models.CharField(max_length=255)),
                ('businessImpact', models.CharField(max_length=255)),
                ('numberOfCustomersImpacted', models.IntegerField()),
                ('patchComplexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20)),
                ('patchUrl', models.CharField(max_length=255)),
                ('patchOs', models.CharField(max_length=255)),
                ('exploitsName', models.CharField(max_length=255)),
                ('exploitsDescription', models.TextField()),
                ('exploitsComplexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='', max_length=20)),
                ('exploitsDependency', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=20)),
                ('tags', models.TextField(default='[]')),
                ('tasksDependencyType', models.IntegerField()),
                ('resolutionNotes', models.TextField()),
                ('resolutionNotesHTML', models.TextField()),
                ('attachments', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vulId', models.IntegerField()),
                ('createdTicketId', models.CharField(default=None, max_length=255)),
                ('organizationId', models.IntegerField(default=None)),
                ('ticketServicePlatform', models.CharField(choices=[('jira', 'JIRA'), ('freshservice', 'Freshservice')], default='', max_length=20)),
            ],
        ),
    ]
